# docker-compose.yml

version: '2'
services:
  boca:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgres-boca
    environment:
      DBHOST: postgres-boca
      DBUSER: bocauser
      DBNAME: bocadb
      DBPASS: boca  
    links:
      - postgres-boca
    networks:
      - boca-network  
    restart: always
  postgres-boca:
    image: postgres
    container_name: postgres-boca
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bocauser
      POSTGRES_PASSWORD: boca
    networks:
      - boca-network  
volumes:
  pgdata:
networks:
 boca-network:
   driver: bridge
   ipam:
     config:
       - subnet: 192.169.1.1/16
